### ISSUE TITLE
Support multiple teams in TrueSkill algorithms

### ISSUE THREAD

**Issue by atomflunder** [atomflunder/skillratings#8]
TrueSkill has the capability of supporting multiple teams just like the WengLin algorithm, and we should implement this.

This means that these functions should be implemented for the TrueSkill algorithm:

- trueskill_multi_team (In Progress!)
- draw_probability_multi_team ([Done](https://github.com/atomflunder/skillratings/pull/9/commits/08ab28cb9a58a2067e8eca0dd0eb8219afcfc4da))
- expected_score_multi_team ([Done](https://github.com/atomflunder/skillratings/pull/9/commits/210f0a3c6516bad7ebf1470f6b3adac111e79edd))

Resources: 

- https://www.moserware.com/assets/computing-your-skill/The%20Math%20Behind%20TrueSkill.pdf
- https://www.microsoft.com/en-us/research/wp-content/uploads/2006/01/TR-2006-80.pdf

**Comment by asyncth** [comment]
I would love to help with this, but I've read the "Computing Your Skill" blog post, started reading "The Math Behind TrueSkill" paper and I still don't really understand anything at all.

**Comment by atomflunder** [comment]
@asyncth Thanks for your interest, I am pretty much in the same boat. It is incredibly complicated. I implemented the `trueskill_multi_team` and `draw_probability_multi_team` but the actual `trueskill_multi_team` is still missing.

I looked around at multiple different implementations, but all of the **properly** working ones are all using different forms of inheritance, none of which I am sure how to port to Rust. Also most are in languages I have zero experience in.  
The implementations without inheritance are either all completely non-functional, or missing team support (Only FFA).

Here are the two working approaches I found:

- https://github.com/sublee/trueskill
- https://github.com/moserware/Skills

All of the other implementations I found on GitHub were ports of these two to different languages, and lots of them are not even working properly.

I tried implementing it but everything so far failed miserably. Not giving up yet, but I am glad of all the help I can get.

**Comment by asyncth** [comment]
I'm not even sure what does one need to do to implement TrueSkill 1v1 though, am I missing something?

**Comment by atomflunder** [comment]
> I'm not even sure what does one need to do to implement TrueSkill 1v1 though, am I missing something?

For the TrueSkill 1v1 and Team v Team functions I went off the implementations on the https://github.com/moserware/Skills repository, where the author uses some shortcuts and not the whole factor graph to calculate the ratings, which made things considerably easier.
